#include "ObjExport.h"

#include <cstdio>

namespace KrautCLI
{
  static const char* const s_BranchTypeNames[Kraut::BranchType::ENUM_COUNT] = {
    "Trunk_1", "Trunk_2", "Trunk_3",
    "Main_Branches_1", "Main_Branches_2", "Main_Branches_3",
    "Sub_Branches_1", "Sub_Branches_2", "Sub_Branches_3",
    "Twigs_1", "Twigs_2", "Twigs_3",
  };

  static const char* const s_GeometryTypeNames[Kraut::BranchGeometryType::ENUM_COUNT] = {
    "Branch", "Frond", "Leaf",
  };

  const char* GetBranchTypeName(aeUInt32 uiType)
  {
    if (uiType >= Kraut::BranchType::ENUM_COUNT)
      return "Unknown";
    return s_BranchTypeNames[uiType];
  }

  const char* GetGeometryTypeName(aeUInt32 uiType)
  {
    if (uiType >= Kraut::BranchGeometryType::ENUM_COUNT)
      return "Unknown";
    return s_GeometryTypeNames[uiType];
  }

  bool ExportObj(const TreeFile& treeFile, const GeneratedTree& tree, const char* szPath, aeString& out_sError)
  {
    std::FILE* pFile = std::fopen(szPath, "wt");
    if (!pFile)
    {
      out_sError = "Could not open OBJ file for writing.";
      return false;
    }

    const float fScale = treeFile.m_fExportScale;

    std::fprintf(pFile, "# Kraut tree mesh (generated by KrautCLI)\n");
    std::fprintf(pFile, "# Branches: %u\n", (unsigned int)tree.m_Structure.m_BranchStructures.size());

    aeUInt32 uiVertexOffset = 1; // OBJ indices are 1-based

    for (aeUInt32 b = 0; b < tree.m_Structure.m_BranchStructures.size(); ++b)
    {
      const Kraut::BranchMesh& branchMesh = tree.m_Mesh.m_BranchMeshes[b];
      const aeUInt32 uiTypeIdx = tree.m_Structure.m_BranchStructures[b].m_Type;

      for (aeUInt32 mt = 0; mt < Kraut::BranchGeometryType::ENUM_COUNT; ++mt)
      {
        const Kraut::Mesh& mesh = branchMesh.m_Mesh[mt];
        if (mesh.m_Triangles.empty())
          continue;

        std::fprintf(pFile, "g %s_%s_%u\n", GetBranchTypeName(uiTypeIdx), GetGeometryTypeName(mt), b);
        std::fprintf(pFile, "usemtl %s_%s\n", GetBranchTypeName(uiTypeIdx), GetGeometryTypeName(mt));

        for (aeUInt32 v = 0; v < mesh.m_Vertices.size(); ++v)
        {
          const Kraut::Vertex& vtx = mesh.m_Vertices[v];

          const float u = (vtx.m_vTexCoord.z != 0.0f) ? (vtx.m_vTexCoord.x / vtx.m_vTexCoord.z) : 0.0f;
          const float t = (vtx.m_vTexCoord.z != 0.0f) ? (vtx.m_vTexCoord.y / vtx.m_vTexCoord.z) : 0.0f;

          std::fprintf(pFile, "v %f %f %f\n", fScale * vtx.m_vPosition.x, fScale * vtx.m_vPosition.y, fScale * vtx.m_vPosition.z);
          std::fprintf(pFile, "vt %f %f\n", u, t);
          std::fprintf(pFile, "vn %f %f %f\n", vtx.m_vNormal.x, vtx.m_vNormal.y, vtx.m_vNormal.z);
        }

        for (aeUInt32 tri = 0; tri < mesh.m_Triangles.size(); ++tri)
        {
          const Kraut::Triangle& t = mesh.m_Triangles[tri];
          const aeUInt32 a = uiVertexOffset + t.m_uiVertexIDs[0];
          const aeUInt32 b2 = uiVertexOffset + t.m_uiVertexIDs[1];
          const aeUInt32 c = uiVertexOffset + t.m_uiVertexIDs[2];
          std::fprintf(pFile, "f %u/%u/%u %u/%u/%u %u/%u/%u\n", a, a, a, b2, b2, b2, c, c, c);
        }

        uiVertexOffset += mesh.m_Vertices.size();
      }
    }

    std::fclose(pFile);
    return true;
  }
} // namespace KrautCLI
